from tkinter import *
root=Tk()
def click(event):
    global scvalue
    #print("Hello")
    text=event.widget.cget("text")
    print(text)
    if text=="=":
        if scvalue.get().isdigit():
            value=int(scvalue.get())
        else:
            value=eval(screen.get())
        scvalue.set(value)
        screen.update()
    elif text=="C":
        scvalue.set("")
        screen.update()
    else:
        scvalue.set(scvalue.get()+text)
        screen.update()

root.geometry("644x900")
root.title("Calculator")
#root.wm_iconbitmap("download.ico")
scvalue=StringVar()
scvalue.set("")
screen=Entry(root,textvar=scvalue,font="lucida 20 bold")
screen.pack(fill=X,ipadx=8,pady=10,padx=10)
frame1=Frame(root,bg="grey")
button=Button(frame1,text="9",padx=15,pady=5,font="lucida 15 bold")
button.pack(side=LEFT,padx=5,pady=8)
button.bind("<Button-1>",click)
button=Button(frame1,text="8",padx=15,pady=5,font="lucida 15 bold")
button.pack(side=LEFT,padx=5,pady=8)
button.bind("<Button-1>",click)
button=Button(frame1,text="7",padx=15,pady=5,font="lucida 15 bold")
button.pack(side=LEFT,padx=5,pady=8)
button.bind("<Button-1>",click)
frame1.pack()
#next
frame1=Frame(root,bg="grey")
button=Button(frame1,text="6",padx=15,pady=5,font="lucida 15 bold")
button.pack(side=LEFT,padx=5,pady=8)
button.bind("<Button-1>",click)
button=Button(frame1,text="5",padx=15,pady=5,font="lucida 15 bold")
button.pack(side=LEFT,padx=5,pady=8)
button.bind("<Button-1>",click)
button=Button(frame1,text="4",padx=15,pady=5,font="lucida 15 bold")
button.pack(side=LEFT,padx=5,pady=8)
button.bind("<Button-1>",click)
frame1.pack()
#next
frame1=Frame(root,bg="grey")
button=Button(frame1,text="3",padx=15,pady=5,font="lucida 15 bold")
button.pack(side=LEFT,padx=5,pady=8)
button.bind("<Button-1>",click)
button=Button(frame1,text="2",padx=15,pady=5,font="lucida 15 bold")
button.pack(side=LEFT,padx=5,pady=8)
button.bind("<Button-1>",click)
button=Button(frame1,text="1",padx=15,pady=5,font="lucida 15 bold")
button.pack(side=LEFT,padx=5,pady=8)
button.bind("<Button-1>",click)
frame1.pack()
#next
frame1=Frame(root,bg="grey")
button=Button(frame1,text="0",padx=15,pady=6,font="lucida 15 bold")
button.pack(side=LEFT,padx=5,pady=8)
button.bind("<Button-1>",click)
button=Button(frame1,text="-",padx=15,pady=6,font="lucida 15 bold")
button.pack(side=LEFT,padx=5,pady=8)
button.bind("<Button-1>",click)
button=Button(frame1,text="*",padx=15,pady=6,font="lucida 15 bold")
button.pack(side=LEFT,padx=5,pady=8)
button.bind("<Button-1>",click)
frame1.pack()
#next
frame1=Frame(root,bg="grey")
button=Button(frame1,text="/",padx=15,pady=5,font="lucida 15 bold")
button.pack(side=LEFT,padx=5,pady=8)
button.bind("<Button-1>",click)
button=Button(frame1,text="%",padx=15,pady=5,font="lucida 15 bold")
button.pack(side=LEFT,padx=5,pady=8)
button.bind("<Button-1>",click)
button=Button(frame1,text="=",padx=15,pady=5,font="lucida 15 bold")
button.pack(side=LEFT,padx=5,pady=8)
button.bind("<Button-1>",click)
frame1.pack()
#next
frame1=Frame(root,bg="grey")
button=Button(frame1,text="C",padx=15,pady=5,font="lucida 15 bold")
button.pack(side=LEFT,padx=5,pady=8)
button.bind("<Button-1>",click)
button=Button(frame1,text="+",padx=15,pady=5,font="lucida 15 bold")
button.pack(side=LEFT,padx=5,pady=8)
button.bind("<Button-1>",click)
button=Button(frame1,text="7",padx=15,pady=5,font="lucida 15 bold")
button.pack(side=LEFT,padx=5,pady=8)
button.bind("<Button-1>",click)
frame1.pack()
root.mainloop()
