a=int(input("Enter a: "))
b=int(input("Enter b: "))
print("Arithmetic Operations: ")
print(f"+: {a+b}")
print(f"-: {a-b}")
print(f"*: {a*b}")
print(f"/: {a/b}")
print(f"//: {a//b}")
print(f"**: {a**b}")
